#!/bin/sh
set -eu

TEMPLATE_PATH="/etc/proxysql.cnf.template"
CONFIG_PATH="/etc/proxysql.cnf"

: "${PROXYSQL_ADMIN_USER:=admin}"
: "${PROXYSQL_ADMIN_PASSWORD:=admin}"
: "${PROXYSQL_ADMIN_PORT:=6032}"
: "${PROXYSQL_PORT:=3306}"
: "${PROXYSQL_THREADS:=4}"
: "${PROXYSQL_MAX_CONNECTIONS:=200}"
: "${PROXYSQL_STATS_USER:=$PROXYSQL_ADMIN_USER}"
: "${PROXYSQL_STATS_PASSWORD:=$PROXYSQL_ADMIN_PASSWORD}"

if [ -z "${DB_USER:-}" ] || [ -z "${DB_PASSWORD:-}" ]; then
  echo "DB_USER and DB_PASSWORD are required for ProxySQL user setup." >&2
  exit 1
fi

: "${PROXYSQL_MONITOR_USER:=$DB_USER}"
: "${PROXYSQL_MONITOR_PASSWORD:=$DB_PASSWORD}"
: "${MYSQL_MASTER_HOST:=db}"
: "${MYSQL_REPLICA_HOST:=db_replica}"
: "${MYSQL_PORT:=3306}"

if [ ! -f "$TEMPLATE_PATH" ]; then
  echo "ProxySQL config template not found at $TEMPLATE_PATH." >&2
  exit 1
fi

escape_sed() {
  printf '%s' "$1" | sed -e 's/[&|]/\\&/g'
}

ADMIN_USER_ESCAPED="$(escape_sed "$PROXYSQL_ADMIN_USER")"
ADMIN_PASSWORD_ESCAPED="$(escape_sed "$PROXYSQL_ADMIN_PASSWORD")"
ADMIN_PORT_ESCAPED="$(escape_sed "$PROXYSQL_ADMIN_PORT")"
PORT_ESCAPED="$(escape_sed "$PROXYSQL_PORT")"
THREADS_ESCAPED="$(escape_sed "$PROXYSQL_THREADS")"
MAX_CONNECTIONS_ESCAPED="$(escape_sed "$PROXYSQL_MAX_CONNECTIONS")"
STATS_USER_ESCAPED="$(escape_sed "$PROXYSQL_STATS_USER")"
STATS_PASSWORD_ESCAPED="$(escape_sed "$PROXYSQL_STATS_PASSWORD")"
MONITOR_USER_ESCAPED="$(escape_sed "$PROXYSQL_MONITOR_USER")"
MONITOR_PASSWORD_ESCAPED="$(escape_sed "$PROXYSQL_MONITOR_PASSWORD")"
DB_USER_ESCAPED="$(escape_sed "$DB_USER")"
DB_PASSWORD_ESCAPED="$(escape_sed "$DB_PASSWORD")"
MASTER_HOST_ESCAPED="$(escape_sed "$MYSQL_MASTER_HOST")"
REPLICA_HOST_ESCAPED="$(escape_sed "$MYSQL_REPLICA_HOST")"
MYSQL_PORT_ESCAPED="$(escape_sed "$MYSQL_PORT")"

sed \
  -e "s|__PROXYSQL_ADMIN_USER__|$ADMIN_USER_ESCAPED|g" \
  -e "s|__PROXYSQL_ADMIN_PASSWORD__|$ADMIN_PASSWORD_ESCAPED|g" \
  -e "s|__PROXYSQL_ADMIN_PORT__|$ADMIN_PORT_ESCAPED|g" \
  -e "s|__PROXYSQL_PORT__|$PORT_ESCAPED|g" \
  -e "s|__PROXYSQL_THREADS__|$THREADS_ESCAPED|g" \
  -e "s|__PROXYSQL_MAX_CONNECTIONS__|$MAX_CONNECTIONS_ESCAPED|g" \
  -e "s|__PROXYSQL_STATS_USER__|$STATS_USER_ESCAPED|g" \
  -e "s|__PROXYSQL_STATS_PASSWORD__|$STATS_PASSWORD_ESCAPED|g" \
  -e "s|__PROXYSQL_MONITOR_USER__|$MONITOR_USER_ESCAPED|g" \
  -e "s|__PROXYSQL_MONITOR_PASSWORD__|$MONITOR_PASSWORD_ESCAPED|g" \
  -e "s|__DB_USER__|$DB_USER_ESCAPED|g" \
  -e "s|__DB_PASSWORD__|$DB_PASSWORD_ESCAPED|g" \
  -e "s|__MYSQL_MASTER_HOST__|$MASTER_HOST_ESCAPED|g" \
  -e "s|__MYSQL_REPLICA_HOST__|$REPLICA_HOST_ESCAPED|g" \
  -e "s|__MYSQL_PORT__|$MYSQL_PORT_ESCAPED|g" \
  "$TEMPLATE_PATH" > "$CONFIG_PATH"

exec proxysql -f -c "$CONFIG_PATH"
