apiVersion: 1
groups:
    - orgId: 1
      name: CPU
      folder: ALERTAS
      interval: 30s
      rules:
        - uid: ffkgiix3j8ykgf
          title: CPU OVERLOAD 90%
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: 100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])))
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 90
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            summary: CPU supera el 90% del l'ús
          isPaused: false
          notification_settings:
            receiver: Telegram
    - orgId: 1
      name: DOCKERS
      folder: ALERTAS
      interval: 1m
      rules:
        - uid: ffl8i97e5s3y8f
          title: Docker container status
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: time() - container_last_seen{name!=""}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: $B > 60
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: math
          noDataState: OK
          execErrState: Error
          keepFiringFor: 2m
          annotations:
            description: Este contenedor ha dejado de responder. Revisa su estado con "docker ps" o mira los logs.
            summary: Contenedor Caído
          isPaused: false
          notification_settings:
            receiver: Telegram
